language: cpp
compiler:
  - gcc
before_install:
  - deb http://ppa.launchpad.net/zoogie/sdl2-snapshots/ubuntu precise main 
  - deb-src http://ppa.launchpad.net/zoogie/sdl2-snapshots/ubuntu precise main
  - sudo apt-get install cmake
  - sudo apt-get install libsdl2 libsdl2-image
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make

