language: cpp
compiler:
  - gcc
before_install:
  - pwd
  - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install libsdl2 libsdl2-image
  - ls /usr/include/
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make

